### PR TITLE
Tweak Chacha and Blake diagonalization to hide latency on b

### PR DESCRIPTION
**Pull request by grafi-tt**
Same change as https://github.com/sneves/blake2-avx2/pull/4

It should improve speed, but I wasn't able to run `cargo bench` on my machine. The test `cargo test` is passing.

### CODE REVIEW

**Comment by kazcw** [comment]
Hi @grafi-tt, thanks for the contribution! That's a nice insight that the diagonalization can be pivoted to move shuffles off the hot path.

I fixed the benchmarks to make this testable, and I found it's actually 3% slower on my machine. This is because the sse4.1 implementation is throughput-bound, and I presume the write-to-read "negative latency" has become high enough to cause register read stalls on my Nehalem machine (which wouldn't be a problem on any newer uarch, with a sane number of register read ports).

This shouldn't be an issue for avx2, which will be latency-bound, and is a current WIP (#17). So once that lands I'll look at how we might be able to get this big performance increase on avx2 without penalizing sse performance. This'll definitely be a big win, but I don't want to make the slowest machines slower in the process!

**Comment by grafi-tt** [comment]
@kazcw Thanks you very much for detailed investigation.

Maybe latency isn't a problem on SSE4.1 because there are load/stores for spilled registers. I'll conduct experiments on my machines later. And I agree that Nehalem machine shouldn't be slowed down.

**Comment by grafi-tt** [comment]
I noticed instruction issue ports are shared by SIMD ALU (expect shift) and SIMD shuffle on Nehalem. (Documented on Intel's manual.) So increasing overlap of ALU operations and shuffles wouldn't make sense. Actually latency itself can't be a problem as `pshufd`'s latency has been 1.

**Comment by kazcw** [comment]
@grafi-tt: The reason this particular SSE implementation is throughput-bound is we're doing 4 ChaCha rounds in tandem; since each ChaCha has an ILP factor of nearly 1.5, that gives a theoretical max IPC of about 6--more than the number of execution units available for SSE2 ops on any processor, so it keeps the whole core busy.

I have just now merged avx2 support into the simd library (in ppv-lite86 0.2.3), and since (4 rounds) / (2 ops/avx instruction) * (1.5 ILP/round) == only 3 IPC max, avx2 does bottleneck on inter-iteration latency and that's why it benefits from moving ops off the critical path. I have to think about whether there's a way to get this benefit without slowing down my old Nehalem.

So far I've been able to avoid any platform-specific code in the crypto implementation and leave all that to the SIMD library, but this represents an inevitable leak in that abstraction--since only the high-level (crypto) code knows where we stand on the latency/throughput tradeoff and can address read stalls.

I'm going to leave this open while we find a way to make this work, because it's a big improvement for avx2

**Comment by kazcw** [comment]
Looked at this again. I found one small change that avoids the performance regression on Nehalem, and now this is faster across the board. Thanks again for this!

**Pull request merged**
