### PR TITLE
Fix some unsoundness and remove some unsafe

### PR DESCRIPTION
**Pull request by joshlf**
Some code relied on the layout of types with no `#[repr(...)]` attribute, which is unsound since the layout of these types is not guaranteed by rustc. This change adds the appropriate `repr` attributes and replaces unsafe code with safe code where possible.

### CODE REVIEW

**Comment by joshlf** [comment]
Friendly ping 🙂

**Comment by gendx** [comment]
FYI, given that the title mentions "unsoundness", I've opened an issue to file a security advisory for this: https://github.com/rustsec/advisory-db/issues/1984.

**Comment by kazcw** [comment]
@joshlf Thank you for contribution. This crate has many users, and some have very specific needs; there is a lot to consider when adding a new dependency. I have finally been able to make the time to evaluate it, and I don't see any problems. The `repr` fixes are important, and reducing usage of `unsafe` is nice too.

**Comment by joshlf** [comment]
Thanks for the review!

**Comment by rukai** [comment]
Hi, this PR added a dependency for zerocopy 0.6, can the project update to zerocopy 0.7 ?
Most projects are already on 0.7 so this has added a new dependency for me.

**Pull request merged**
